# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bd312a3987391751432190cdbece1f3cc286613a35d91a70fe320ca890485ac5f541ae901675d39f8793cbc7ba9662ccf2acfd3bd7344573911546ad9846e95c

test:
  secret_key_base: 44b740e749dd525f3b21b94e14478e09b58a44b3aa05dc86280f943585be1c7ad2d748acfcdfdf536520f42eafab4d4c8118fc07c1f42052852929cfea310027

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
